let nyCounties = [
    {label: 'Select State', value: null},
    {label: 'Albany County', value: 'Albany County'},
    {label: 'Allegany County', value: 'Allegany County'},
    {label: 'Bronx County', value: 'Bronx County'},
    {label: 'Broome County', value: 'Broome County'},
    {label: 'Cattaraugus County', value: 'Cattaraugus County'},
    {label: 'Cayuga County', value: 'Cayuga County'},
    {label: 'Chautauqua County', value: 'Chautauqua County'},
    {label: 'Chemung County', value: 'Chemung County'},
    {label: 'Chenango County', value: 'Chenango County'},
    {label: 'Clinton County', value: 'Clinton County'},
    {label: 'Columbia County', value: 'Columbia County'},
    {label: 'Cortland County', value: 'Cortland County'},
    {label: 'Delaware County', value: 'Delaware County'},
    {label: 'Dutchess County', value: 'Dutchess County'},
    {label: 'Erie County', value: 'Erie County'},
    {label: 'Essex County', value: 'Essex County'},
    {label: 'Franklin County', value: 'Franklin County'},
    {label: 'Fulton County', value: 'Fulton County'},
    {label: 'Genesee County', value: 'Genesee County'},
    {label: 'Greene County' ,value: 'Greene County'},
    {label: 'Hamilton County', value: 'Hamilton County'},
    {label: 'Herkimer County' ,value: 'Herkimer County'},
    {label: 'Jefferson County', value: 'Jefferson County'},
    {label: 'Kings County (Brooklyn)', value: 'Kings County (Brooklyn)'},
    {label: 'Lewis County', value: 'Lewis County'},
    {label: 'Livingston County', value: 'Livingston County'},
    {label: 'Madison County', value: 'Madison County'},
    {label: 'Monroe County' ,value: 'Monroe County'},
    {label: 'Montgomery County', value: 'Montgomery County'},
    {label: 'Nassau County', value: 'Nassau County'},
    {label: 'New York County (Manhattan)', value: 'New York County (Manhattan)'},
    {label: 'Niagara County' ,value: 'Niagara County'},
    {label: 'Oneida County' ,value: 'Oneida County'},
    {label: 'Onondaga County', value: 'Onondaga County'},
    {label: 'Ontario County' ,value: 'Ontario County'},
    {label: 'Orange County' ,value: 'Orange County'},
    {label: 'Orleans County', value: 'Orleans County'},
    {label: 'Oswego County', value: 'Oswego County'},
    {label: 'Otsego County', value: 'Otsego County'},
    {label: 'Putnam County', value: 'Putnam County'},
    {label: 'Queens County', value: 'Queens County'},
    {label: 'Rensselaer County', value: 'Rensselaer County'},
    {label: 'Richmond County (Staten Island)', value: 'Richmond County (Staten Island)'},
    {label: 'Rockland County', value: 'Rockland County'},
    {label: 'Saint Lawrence County' ,value: 'Saint Lawrence County'},
    {label: 'Saratoga County', value: 'Saratoga County'},
    {label: 'Schenectady County', value: 'Schenectady County'},
    {label: 'Schoharie County' ,value: 'Schoharie County'},
    {label: 'Schuyler County', value: 'Schuyler County'},
    {label: 'Seneca County', value: 'Seneca County'},
    {label: 'Steuben County', value: 'Steuben County'},
    {label: 'Suffolk County' ,value: 'Suffolk County'},
    {label: 'Sullivan County', value: 'Sullivan County'},
    {label: 'Tioga County', value: 'Tioga County'},
    {label: 'Tompkins County', value: 'Tompkins County'},
    {label: 'Ulster County' ,value: 'Ulster County'},
    {label: 'Warren County' ,value: 'Warren County'},
    {label: 'Washington County', value: 'Washington County'},
    {label: 'Wayne County', value: 'Wayne County'},
    {label: 'Westchester County', value: 'Westchester County'},
    {label: 'Wyoming County', value: 'Wyoming County'},
    {label: 'Yates County', value: 'Yates County'} ,
]

export default nyCounties